// const first = document.getElementById("first")
// const divchild = document.getElementById("parent")
// console.log(first.parentNode)
// console.log(first.parentElement)
// console.log(divchild.parentNode)
// console.log(divchild.parentElement)

// console.log(divchild.childNodes)
// console.log(divchild.children)
// console.log(divchild.firstChild)
// console.log(divchild.lastChild)
// console.log(divchild.firstElementChild)
// console.log(divchild.lastElementChild)

// const list1 = document.getElementById("list1")
// console.log(list1.parentElement)
// console.log(list1.childNodes)
// console.log(list1.children)
// console.log(list1.firstChild)
// console.log(list1.lastChild)
// console.log(list1.firstElementChild)
// console.log(list1.lastElementChild)
// console.log()
// console.log(document.parentElement)
// console.log(document)

const mainparent1 = document
console.log(mainparent1)
const parent1 = document.documentElement
console.log(parent1)
console.log(mainparent1.parentNode)
console.log(mainparent1.parentElement)
console.log(parent1.parentNode)
console.log(parent1.parentElement)

const par1 = document.getElementById("parent1")
console.log(par1.parentNode)
console.log(par1.parentElement)

const list2 = document.getElementById("list2")
const mango = document.getElementById("mango")
console.log(mango.nextSibling) 
console.log(mango.nextElementSibling)
console.log(mango.previousSibling) 
console.log(mango.previousElementSibling)

console.log()
console.log(document)
console.log(document.documentElement)
console.log(document.documentElement.lastElementChild.firstElementChild.nextElementSibling.firstElementChild.nextElementSibling)
